
project_id = "inbfxduleyhygxatxmre"

[functions.chat]
verify_jwt = true

[functions.analyze-plant]
verify_jwt = true

[functions.create-storage-bucket]
verify_jwt = false

[functions.mark-quiz-completed]
verify_jwt = true

[functions.square-webhook]
verify_jwt = false

