
# A string used to distinguish different Supabase projects on the same host. Defaults to the project reference.
project_id = "inbfxduleyhygxatxmre"

# This is a JWT secret that will be used to sign JWT tokens for authenticated requests.
# You may use this to authenticate users into your Edge Functions. To get the JWT token,
# use Supabase Auth and select 'Generate JWT Token' in the dashboard.
jwt_secret = ""
anon_key = ""
service_role_key = ""

[functions.square-webhook]
verify_jwt = false
