import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import SEOHead from '@/components/SEOHead';
import '@/components/landing/premium.css';

const services = [
  ['AI tools for everyday observations', 'MasterGrowbot brings AI into a practical, accessible workflow. Start with your own photographs and records, and keep human judgment in charge of what happens next.'],
  ['GrowTech equipment', 'Phone lenses and independent monitoring tools help you collect photographs and readings. Choose the tool you need; hardware purchases do not include an app subscription or automatic syncing.'],
  ['Playbooks and quickstarts', 'Illustrated references turn an unfamiliar tool into a repeatable observation routine. Download the PDFs, use the worksheets and keep records you can return to.'],
];
const differences = [
  ['Commercial experience, made approachable', 'MasterGrowbot draws on experience building and selling AI technology for commercial cannabis businesses. We bring those ideas into practical tools that home growers and small craft cultivators can understand and use.'],
  ['Observation before assumption', 'Our new Playbook separates visible evidence, missing context and interpretation. An AI response is something to check, rather than a verdict to follow.'],
  ['Your records stay useful', 'The guides include printable worksheets and a CSV log. Keep original photographs and manual readings in a folder or spreadsheet you control.'],
  ['Clear product boundaries', 'Hardware, digital guides and app access are separate purchases. The GrowTech Equipment Quickstart is $19 once; the Playbook has its own one-time price and includes that quickstart.'],
  ['A starting point you can inspect', 'Read a free sample before buying a guide. See the actual format, writing and worksheets so you can decide whether the workflow fits you.'],
];
const facts = [
  ['Company name', 'MasterGrowbot AI · AGCOM SOLUTIONS LLC'], ['Type', 'AI tools, observation equipment and digital education'], ['Website', 'www.mastergrowbot.com'], ['Core offering', 'Practical tools for home growers and small craft cultivators'], ['Pricing', 'GrowTech hardware packages from $99; Equipment Quickstart $19 once; complete AI Plant Observation Playbook kit $29 once'], ['Contract terms', 'Digital guides and GrowTech hardware are one-time purchases. App pricing is listed in the app stores.'], ['Communication', 'support@mastergrowbot.com and the website contact page'], ['Delivery', 'Digital files through the Whop account used to purchase; hardware shipping details at checkout'],
];
const faq = [
  ['What is MasterGrowbot here to do?', 'Bring AI experience from commercial cannabis technology into practical tools for home growers and small craft cultivators. Our aim is to help people become more confident, careful observers with records they can trust.'],
  ['Is the Playbook a growing recipe?', 'No. The AI Plant Observation Playbook teaches photographs, manual records, AI prompts, uncertainty checks and journals. It does not provide cultivation instructions, treatment recipes or guaranteed outcomes.'],
  ['Do I need all the GrowTech tools?', 'No. The observation workflow starts with a phone and a simple record. Equipment is optional, and each tool operates independently.'],
  ['Are the app and guides included with hardware?', 'The app is separate. Basic equipment setup sheets are free; the camera-and-quickstart bundle includes the paid Equipment Quickstart Guide as stated on its product page.'],
  ['How can I get help with my purchase?', 'Use the Whop account and receipt from checkout to find your digital purchases. For access or equipment questions, contact support@mastergrowbot.com with your order details.'],
];
export default function About() {
  return <div className="premium-site min-h-screen bg-[#030906] text-white">
    <SEOHead title="About MasterGrowbot AI | Our mission" description="MasterGrowbot AI makes practical AI tools, observation equipment and clear digital guides accessible to home growers and small craft cultivators in legal markets." canonicalUrl="https://www.mastergrowbot.com/about" ogImage="https://www.mastergrowbot.com/images/playbook/about-social-v2.webp" />
    <Helmet><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'AboutPage',url:'https://www.mastergrowbot.com/about',name:'About MasterGrowbot AI',mainEntity:{'@type':'Organization',name:'MasterGrowbot AI',legalName:'AGCOM SOLUTIONS LLC',url:'https://www.mastergrowbot.com',email:'support@mastergrowbot.com'}})}</script></Helmet>
    <LandingNav />
    <main className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24">
      <div className="grid items-center gap-12 lg:grid-cols-2">
        <div><p className="text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">The MasterGrowbot AI mission</p><h1 className="mt-5 text-4xl font-bold leading-[1.08] tracking-tight sm:text-6xl">Your craft.<br /><span className="text-emerald-300">Your curiosity.</span><br />Practical AI.</h1><p className="mt-7 text-xl leading-8 text-white/75">MasterGrowbot AI is a tools and education brand that makes plant observation more practical for home growers and small craft cultivators.</p><p className="mt-5 leading-7 text-white/60">Our mission is to make practical AI technology accessible to home growers and small craft cultivators in legal markets. You bring the care and curiosity. We bring approachable tools, clear references and a way to keep your observations useful.</p><Link to="/playbooks" className="mt-8 inline-flex rounded-full bg-emerald-300 px-7 py-4 font-bold text-black">Explore Playbooks & Quickstarts →</Link><Link to="/grow-tech" className="mt-4 inline-flex px-7 py-4 font-semibold text-emerald-200 underline underline-offset-4">Explore GrowTech equipment →</Link></div>
        <section aria-label="Our mission in practice" className="rounded-3xl border border-emerald-300/20 bg-[#10271f] p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Our mission in practice</p><h2 className="mt-5 text-3xl font-bold leading-tight">More confidence in your craft. A clearer starting point with AI.</h2><div className="mt-8 space-y-6">{[['Accessible technology','Give people a clear starting point, useful prompts and a way to check the answers.'],['Useful records','Help people capture photographs and manual readings with context they can understand later.'],['Understandable guidance','Preserve original records, identify uncertainty and let human judgment guide the next step.']].map(([title,text])=><article key={title} className="border-t border-white/15 pt-5"><h3 className="font-semibold text-emerald-200">{title}</h3><p className="mt-2 text-sm leading-6 text-white/70">{text}</p></article>)}</div></section>
      </div>
      <section className="mt-24"><h2 className="text-3xl font-bold">What MasterGrowbot does</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{services.map(([title,text])=><article key={title} className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">What makes MasterGrowbot different</h2><div className="mt-8 grid gap-8 md:grid-cols-2">{differences.map(([title,text],i)=><article key={title}><p className="text-sm text-emerald-300">0{i+1}</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20 rounded-3xl bg-emerald-950/40 p-8 sm:p-12"><h2 className="text-3xl font-bold">Who MasterGrowbot is for</h2><ul className="mt-6 grid list-inside list-disc gap-4 text-lg text-white/75 md:grid-cols-2"><li>Home growers building their observation skills</li><li>Small craft cultivators keeping consistent records</li><li>Beginners learning to work with AI critically</li><li>Equipment owners looking for clear setup references</li></ul></section>
      <section className="mt-20 max-w-3xl"><h2 className="text-3xl font-bold">Why MasterGrowbot exists</h2><p className="mt-5 text-lg leading-8 text-white/70">AI tools become useful when people know what to ask, what to record and how to check an answer. MasterGrowbot brings those pieces together for home growers and small craft cultivators, with practical references they can use at their own pace.</p><p className="mt-5 leading-7 text-white/60">You should not need a commercial technology team to begin using AI thoughtfully. MasterGrowbot connects approachable tools with practical education, helping people ask clearer questions, preserve their own evidence and learn at their own pace.</p><Link to="/contact" className="mt-5 inline-block text-emerald-300 underline underline-offset-4">Contact MasterGrowbot</Link></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">How MasterGrowbot works</h2><div className="mt-8 grid gap-7 md:grid-cols-3">{[['Choose a starting point','Browse GrowTech for equipment or read a Playbook sample. App access is available separately through the app stores.'],['Purchase and get access','Pay through Whop. Digital buyers sign in with their checkout account and open Start Here to find the files and suggested reading order.'],['Make it your own','Keep original photos and manual records. Use the worksheets at your own pace, and email support for purchase or access questions.']].map(([title,text])=><article key={title}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">Key facts</h2><div className="mt-7 overflow-x-auto rounded-2xl border border-white/15"><table className="w-full text-left text-sm"><caption className="sr-only">MasterGrowbot company and purchase facts</caption><tbody>{facts.map(([key,value])=><tr key={key} className="border-b border-white/10 last:border-0"><th scope="row" className="w-1/3 px-5 py-4 font-semibold text-white/85">{key}</th><td className="px-5 py-4 leading-6 text-white/65">{value}</td></tr>)}</tbody></table></div></section>
      <section className="mt-20 max-w-3xl"><h2 className="text-3xl font-bold">Frequently asked questions</h2>{faq.map(([question,answer])=><article key={question} className="mt-8"><h3 className="text-xl font-semibold">{question}</h3><p className="mt-3 leading-7 text-white/65">{answer}</p></article>)}</section>
    </main><LandingFooter />
  </div>;
}
