import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import SEOHead from '@/components/SEOHead';
import '@/components/landing/premium.css';

const services = [
  ['AI tools for everyday observations', 'MasterGrowbot brings AI into a practical, accessible workflow. Start with your own photographs and records, and keep human judgment in charge of what happens next.'],
  ['GrowTech equipment', 'Phone lenses and independent monitoring tools help you collect photographs and readings. Choose the tool you need; hardware purchases do not include an app subscription or automatic syncing.'],
  ['Playbooks and quickstarts', 'Illustrated references turn an unfamiliar tool into a repeatable observation routine. Download the PDFs, use the worksheets and keep records you can return to.'],
];
const differences = [
  ['Commercial experience, made approachable', 'Founder Eli Duffy brings experience building and selling AI technology for commercial cannabis businesses. The mission is to make powerful ideas easier for home growers and small craft cultivators to understand and use.'],
  ['Observation before assumption', 'Our new Playbook separates visible evidence, missing context and interpretation. An AI response is something to check, rather than a verdict to follow.'],
  ['Your records stay useful', 'The guides include printable worksheets and a CSV log. Keep original photographs and manual readings in a folder or spreadsheet you control.'],
  ['Clear product boundaries', 'Hardware, digital guides and app access are separate purchases. The GrowTech Equipment Quickstart is $19 once; the Playbook has its own one-time price and includes that quickstart.'],
  ['A starting point you can inspect', 'Read a free sample before buying a guide. See the actual format, writing and worksheets so you can decide whether the workflow fits you.'],
];
const facts = [
  ['Company name', 'MasterGrowbot AI · AGCOM SOLUTIONS LLC'], ['Type', 'AI tools, observation equipment and digital education'], ['Founder', 'Eli Duffy'], ['Website', 'www.mastergrowbot.com'], ['Core offering', 'Practical tools for home growers and small craft cultivators'], ['Pricing', 'GrowTech tools from $59; Equipment Quickstart $19 once; Playbook regular price $89 with a dated $42 launch offer'], ['Contract terms', 'Digital guides and GrowTech hardware are one-time purchases. App pricing is listed in the app stores.'], ['Communication', 'support@mastergrowbot.com and the website contact page'], ['Delivery', 'Digital files through the Whop account used to purchase; hardware shipping details at checkout'],
];
const faq = [
  ['What is MasterGrowbot here to do?', 'Bring AI experience from commercial cannabis technology into practical tools for home growers and small craft cultivators. Our aim is to help people become more confident, careful observers with records they can trust.'],
  ['Is the Playbook a growing recipe?', 'No. The AI Plant Observation Playbook teaches photographs, manual records, AI prompts, uncertainty checks and journals. It does not provide cultivation instructions, treatment recipes or guaranteed outcomes.'],
  ['Do I need all the GrowTech tools?', 'No. The observation workflow starts with a phone and a simple record. Equipment is optional, and each tool operates independently.'],
  ['Are the app and guides included with hardware?', 'The app is separate. Basic equipment setup sheets are free; the camera-and-quickstart bundle includes the paid Equipment Quickstart Guide as stated on its product page.'],
  ['How can I get help with my purchase?', 'Use the Whop account and receipt from checkout to find your digital purchases. For access or equipment questions, contact support@mastergrowbot.com with your order details.'],
];
export default function About() {
  return <div className="premium-site min-h-screen bg-[#030906] text-white">
    <SEOHead title="About MasterGrowbot AI | Eli Duffy and our mission" description="Meet Eli Duffy and the mission behind MasterGrowbot: making commercial AI experience practical for home growers and small craft cultivators." canonicalUrl="https://www.mastergrowbot.com/about" />
    <Helmet><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'AboutPage',url:'https://www.mastergrowbot.com/about',name:'About MasterGrowbot AI',mainEntity:{'@type':'Organization',name:'MasterGrowbot AI',legalName:'AGCOM SOLUTIONS LLC',url:'https://www.mastergrowbot.com',founder:{'@type':'Person',name:'Eli Duffy'},email:'support@mastergrowbot.com'}})}</script></Helmet>
    <LandingNav />
    <main className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24">
      <div className="grid items-center gap-12 lg:grid-cols-2">
        <div><p className="text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Our story · Our mission</p><h1 className="mt-5 text-5xl font-bold leading-[1.08] tracking-tight sm:text-6xl">Big ideas.<br /><span className="text-emerald-300">Practical tools.</span><br />Personal progress.</h1><p className="mt-7 text-xl leading-8 text-white/75">MasterGrowbot is an AI tools and education brand that makes plant observation more practical for home growers and small craft cultivators.</p><p className="mt-5 leading-7 text-white/60">Powerful technology matters when people can use it. That belief connects Eli Duffy’s experience in commercial cannabis technology with the tools, records and references we make today.</p><Link to="/playbooks" className="mt-8 inline-flex rounded-full bg-emerald-300 px-7 py-4 font-bold text-black">Explore the Playbook →</Link></div>
        <figure className="overflow-hidden rounded-3xl border border-white/15"><img src="/images/ai-strategy/eli-arcview-investor-forum.png" alt="Eli Duffy presenting at an Arcview investor forum" className="w-full object-cover" loading="eager" /><figcaption className="bg-white/5 p-5 text-sm text-white/65">Eli Duffy sharing his work in cannabis technology.</figcaption></figure>
      </div>
      <section className="mt-24"><h2 className="text-3xl font-bold">What MasterGrowbot does</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{services.map(([title,text])=><article key={title} className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">What makes MasterGrowbot different</h2><div className="mt-8 grid gap-8 md:grid-cols-2">{differences.map(([title,text],i)=><article key={title}><p className="text-sm text-emerald-300">0{i+1}</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20 rounded-3xl bg-emerald-950/40 p-8 sm:p-12"><h2 className="text-3xl font-bold">Who uses MasterGrowbot</h2><ul className="mt-6 grid list-inside list-disc gap-4 text-lg text-white/75 md:grid-cols-2"><li>Home growers building their observation skills</li><li>Small craft cultivators keeping consistent records</li><li>Beginners learning to work with AI critically</li><li>Equipment owners looking for clear setup references</li></ul></section>
      <section className="mt-20 max-w-3xl"><h2 className="text-3xl font-bold">The team behind MasterGrowbot</h2><h3 className="mt-7 text-2xl font-semibold">Eli Duffy, founder</h3><p className="mt-5 text-lg leading-8 text-white/70">Eli’s work has taken him through commercial cannabis technology, including co-founding and leading Grownetics and creating Growbot. Building and selling technology in that setting showed him how much useful information people can collect—and how difficult it can be to turn that information into something understandable.</p><p className="mt-5 text-lg leading-8 text-white/70">MasterGrowbot carries that experience into a more personal setting: a home grower with a phone, a small craft cultivator with a notebook, someone learning what a tool can and cannot tell them. The ambition is to make the power of AI easy and practical to use, while keeping people’s judgment, curiosity and original records at the center.</p><Link to="/contact" className="mt-5 inline-block text-emerald-300 underline underline-offset-4">Contact MasterGrowbot</Link></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">How MasterGrowbot works</h2><div className="mt-8 grid gap-7 md:grid-cols-3">{[['Choose a starting point','Browse GrowTech for equipment or read a Playbook sample. App access is available separately through the app stores.'],['Purchase and get access','Pay through Whop. Digital buyers sign in with their checkout account and open Start Here to find the files and suggested reading order.'],['Make it your own','Keep original photos and manual records. Use the worksheets at your own pace, and email support for purchase or access questions.']].map(([title,text])=><article key={title}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-white/65">{text}</p></article>)}</div></section>
      <section className="mt-20"><h2 className="text-3xl font-bold">Key facts</h2><div className="mt-7 overflow-x-auto rounded-2xl border border-white/15"><table className="w-full text-left text-sm"><caption className="sr-only">MasterGrowbot company and purchase facts</caption><tbody>{facts.map(([key,value])=><tr key={key} className="border-b border-white/10 last:border-0"><th scope="row" className="w-1/3 px-5 py-4 font-semibold text-white/85">{key}</th><td className="px-5 py-4 leading-6 text-white/65">{value}</td></tr>)}</tbody></table></div></section>
      <section className="mt-20 max-w-3xl"><h2 className="text-3xl font-bold">Frequently asked questions</h2>{faq.map(([question,answer])=><article key={question} className="mt-8"><h3 className="text-xl font-semibold">{question}</h3><p className="mt-3 leading-7 text-white/65">{answer}</p></article>)}</section>
    </main><LandingFooter />
  </div>;
}
