import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Download } from "lucide-react";
import SEOHead from "@/components/SEOHead";
import LandingNav from "@/components/landing/LandingNav";
import LandingFooter from "@/components/landing/LandingFooter";
import LensGallery from "@/components/grow-tech/LensGallery";
import LensTestimonials from "@/components/grow-tech/LensTestimonials";
import { canPurchaseGrowTech, scoutGuideBundle as offer, soilGuideOffer, growTentOffer, type GrowTechProduct } from "@/data/growTechProducts";
import { trackEvent, trackGrowTechSelectItem } from "@/lib/analytics";
import { captureGrowTechAttribution } from "@/lib/growTechAttribution";
import "@/components/landing/premium.css";
import "@/components/grow-tech/lens-launch.css";

function OfferAction({ location, product = offer }: { location: string; product?: GrowTechProduct }) {
  return canPurchaseGrowTech(product) ? <Link className="lens-button" to={`/grow-tech/checkout/${product.anchorId}`} onClick={() => trackGrowTechSelectItem(product, location)}>{product.buttonLabel}<ArrowRight size={18}/></Link>
    : <a className="lens-button" href="#delivery">Ordering opens soon<ArrowRight size={18}/></a>;
}
const questions = [
  ["Is this MasterGrowbot’s own hardware?", "APEXEL makes the physical lens and LED light. MasterGrowbot provides the equipment guide, worksheets and observation log. The package does not include a phone or app subscription."],
  ["Will it work with my phone?", "Check your exact model in APEXEL’s compatibility guide. The clip must align the lens with the main rear camera. Camera bumps and thick cases affect fit; a case may need to be removed. Compatibility is not universal."],
  ["Does it automatically sync to MasterGrowbot?", "No. This is an optical phone accessory. Save or upload photos and notes manually. The worksheets and CSV log work independently of the app."],
  ["Is 10–20X enough for every inspection?", "No single magnification fits every task. APEXEL specifies adjustable 10–20X macro magnification. Focus, lighting and phone compatibility affect results. It does not diagnose plant problems or replace a microscope when greater detail is needed."],
  ["How do I get the digital files?", "After confirmed payment, sign in to Whop with the email on your receipt. The Start Here and Quickstart Files apps contain the guide and templates. Contact support@mastergrowbot.com if access is missing."],
  ["Why does payment show Smart Ag AI?", "MasterGrowbot’s Whop store operates through the Smart Ag AI business. Whop processes the payment. Hardware ordering begins only after verified buyer payment."],
];
export default function GrowTech() {
  useEffect(() => { captureGrowTechAttribution(); trackEvent("growtech_offer_view", {product_id:offer.productId,value:119,currency:"USD",availability:offer.availability}); }, []);
  return <div className="premium-site lens-page">
    <SEOHead title="GrowTech: Macro Lens, Soil Meter & Grow Tent | MasterGrowbot" description="Shop the $119 APEXEL lens package, $99 soil meter package and $199 compact tent preorder. Each includes the MasterGrowbot guide and templates." canonicalUrl="https://www.mastergrowbot.com/grow-tech" ogImage="https://www.mastergrowbot.com/images/grow-tech/lens-launch/product.webp" />
    <LandingNav growTechMode/><main>
      <section id="lens-offer" className="lens-wrap lens-hero"><div className="lens-intro"><p className="lens-eyebrow">GROWTECH · LENS + LIGHT + OBSERVATION KIT</p><h1>Closer plant photos.<br/><em>A clearer way to keep track.</em></h1><p>Get the APEXEL 10–20X macro lens with LED light, plus MasterGrowbot’s equipment guide, printable worksheets and observation log.</p><div className="lens-price"><strong>$119</strong><span>USD · One-time purchase</span></div><p className="lens-small">{offer.fulfillmentNote}</p><OfferAction location="growtech:hero"/><a className="lens-secondary" href="#compatibility">Check phone compatibility ↓</a><p className="lens-small">Whop payment · Phone not included · No app subscription</p><nav aria-label="More GrowTech products" className="lens-product-links"><a href="#soil-meter">Soil meter · $99 ↓</a><a href="#grow-tent">2×2 tent · $199 ↓</a></nav></div><LensGallery/></section>
      <section className="lens-wrap lens-section" id="contents"><p className="lens-eyebrow">ONE PACKAGE. A SIMPLE ROUTINE.</p><h2>Look closer. Save the context.</h2><p className="lens-lede">The lens helps you get closer to small plant details. The guide helps you repeat the setup and keep notes beside each photo.</p><div className="lens-grid"><article><span className="lens-step">01</span><h3>APEXEL lens + LED light</h3><p>Adjustable 10–20X ZoomMacro lens, LED ring light and phone mounting clip. Phone not included. Check your phone and case compatibility before ordering.</p></article><article><span className="lens-step">02</span><h3>MasterGrowbot Quickstart</h3><p>The existing 12-page equipment guide covers a consistent photo routine, handling, reading limitations and troubleshooting. Inspect the sample before buying.</p></article><article><span className="lens-step">03</span><h3>Worksheets + observation log</h3><p>Two printable/fillable worksheets and a CSV log for dates, equipment settings and observations. Use them without an app subscription.</p></article></div><p className="lens-small">Phones, plants, tents and props in the illustrations are not included.</p></section>
      <LensTestimonials/>
      <section className="lens-wrap lens-section lens-split" id="compatibility"><div><p className="lens-eyebrow">CHECK THE FIT FIRST</p><h2>Your phone. Your setup.</h2><p>Check your exact phone model, whether the clip reaches the main rear camera and whether your case prevents alignment. Macro focus needs a close, steady working position.</p><a className="lens-button lens-outline" href="https://www.shopapexel.com/pages/compatibility-guide" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent("growtech_compatibility_click",{product_id:offer.productId})}>Open APEXEL’s compatibility guide ↗</a></div><aside className="lens-panel"><h3>See actual product evidence</h3><p>Inspect APEXEL’s photos, specifications and demonstrations to judge whether this lens suits the detail you need.</p><a className="lens-secondary" href="https://www.shopapexel.com/products/zoommacro-macro-lens?variant=48462996472116" target="_blank" rel="noopener noreferrer">View the manufacturer’s demonstration ↗</a><p className="lens-small">Our gallery contains illustrations, not customer photos or optical performance demonstrations.</p></aside></section>
      <section className="lens-wrap lens-section lens-split" id="guide-preview"><div><p className="lens-eyebrow">INSPECT THE DIGITAL KIT</p><h2>More than another loose photo.</h2><p>Keep the date, the plant and the setup with your observations. The guide and templates give you a repeatable place to start.</p><a className="lens-button lens-outline" href="/downloads/grow-tech/quickstart-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent("growtech_guide_preview",{product_id:offer.productId})}><Download size={18}/> Preview the guide sample</a></div><div className="lens-panel"><img src="/images/playbook/quickstart-cover-v4.webp" alt="MasterGrowbot Equipment Quickstart guide cover illustration" width={480} height={480} loading="lazy" className="lens-guide-cover"/><p className="lens-small">12-page PDF · 2 worksheets · CSV observation log<br/>Files through Whop after confirmed payment.</p></div></section>
      <section className="lens-wrap lens-section lens-split" id="soil-meter"><div><p className="lens-eyebrow">SOIL OBSERVATIONS</p><h2>A reading, with room for your notes.</h2><p>A standalone six-function meter, plus the MasterGrowbot Quickstart and templates. Check soil moisture, pH, temperature, fertility, light and ambient humidity. Treat readings as observations; accuracy depends on conditions and handling.</p><div className="lens-price"><strong>$99</strong><span>USD · One-time purchase</span></div><p className="lens-small">{soilGuideOffer.fulfillmentNote}</p><OfferAction product={soilGuideOffer} location="growtech:soil"/><p className="lens-small">White-cased meter with two probes. No automatic app syncing. Plants and other props are not included.</p></div><LensGallery kind="soil"/></section>
      <section className="lens-wrap lens-section lens-split" id="grow-tent"><div><p className="lens-eyebrow">A SPACE FOR YOUR SMALL GROW</p><h2>Start compact. Keep it organized.</h2><p>An unbranded 2×2 tent with reflective lining, a zip doorway and floor tray. A dedicated space for seedlings and compact plants, plus the same MasterGrowbot Quickstart and observation templates.</p><div className="lens-price"><strong>$199</strong><span>USD · One-time preorder</span></div><p className="lens-small">{growTentOffer.fulfillmentNote}</p><OfferAction product={growTentOffer} location="growtech:tent"/><p className="lens-small">24 × 24 × 48 in (61 × 61 × 122 cm). Tent only: lights, fans, ducting, pots and plants are not included.</p></div><LensGallery kind="tent"/></section>
      <section className="lens-wrap lens-section" id="delivery"><p className="lens-eyebrow">BEFORE YOU ORDER</p><h2>Clear delivery. Real support.</h2><div className="lens-grid"><article><h3>Delivery at a glance</h3><p>Lens and meter: US & Canada, estimated 4–6 weeks. Tent: US preorder, estimated 8–10 weeks.</p><p>Shipping included. Prices in USD; sales tax shown at checkout. Canadian import charges, if assessed, are extra.</p></article><article><h3>Guide now. Tracking to follow.</h3><p>Get the guide and templates through Whop after confirmed payment. Hardware is sourced to order; tracking is provided after dispatch.</p></article><article><h3>Help and returns</h3><p>Email <a href="mailto:support@mastergrowbot.com">support@mastergrowbot.com</a> for fit, delivery or access help. Contact us before returning unused, unopened hardware within 30 days of delivery. You pay return shipping, except for damaged or incorrect goods.</p></article></div></section>
      <section className="lens-wrap lens-section" id="faq"><p className="lens-eyebrow">A FEW GOOD QUESTIONS</p><h2>Before your closer look.</h2>{questions.map(([question,answer])=><details key={question} className="lens-faq"><summary>{question}</summary><p>{answer}</p></details>)}</section>
      <section className="lens-wrap lens-section lens-final"><p className="lens-eyebrow">THE GROWTECH LENS PACKAGE</p><h2>A closer look, with a clearer record.</h2><p>APEXEL lens + LED light. MasterGrowbot guide + templates.</p><p className="lens-price"><strong>$119</strong><span>USD · One time</span></p><OfferAction location="growtech:final"/></section>
    </main><LandingFooter/><div className="lens-sticky"><span><strong>$119</strong> · Lens + guide</span><OfferAction location="growtech:sticky"/></div>
  </div>;
}
