import { Helmet } from "react-helmet-async";
import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Download } from "lucide-react";
import SEOHead from "@/components/SEOHead";
import LandingNav from "@/components/landing/LandingNav";
import LandingFooter from "@/components/landing/LandingFooter";
import LensGallery from "@/components/grow-tech/LensGallery";
import LensTestimonials from "@/components/grow-tech/LensTestimonials";
import ShopDigitalOffers from "@/components/grow-tech/ShopDigitalOffers";
import { canPurchaseGrowTech, scoutGuideBundle as offer, soilGuideOffer, growTentOffer, type GrowTechProduct } from "@/data/growTechProducts";
import { trackEvent, trackGrowTechSelectItem } from "@/lib/analytics";
import { captureGrowTechAttribution } from "@/lib/growTechAttribution";
import "@/components/landing/premium.css";
import "@/components/grow-tech/lens-launch.css";

function OfferAction({ location, product = offer }: { location: string; product?: GrowTechProduct }) {
  return canPurchaseGrowTech(product) ? <Link className="lens-button" to={`/grow-tech/checkout/${product.anchorId}`} onClick={() => trackGrowTechSelectItem(product, location)}>{product.buttonLabel}<ArrowRight size={18}/></Link>
    : <a className="lens-button" href="#delivery">Ordering opens soon<ArrowRight size={18}/></a>;
}
const questions = [
  ["Which GrowTech tool should I choose?", "Choose the lens for closer plant photos, the soil meter for quick spot checks, or the tent for a dedicated compact growing space. Each package includes the Equipment Quickstart and templates. The lens package also includes the complete Playbook kit."],
  ["What comes with my hardware?", "Every hardware package includes the 12-page Equipment Quickstart, two worksheets and a CSV log. The $119 lens package also includes the 32-page Playbook, 8 prompts and 8-page workbook. You can see the exact accessories on each product above and preview the guide before you buy."],
  ["Will the lens fit my phone?", <>Check your model in <a className="lens-secondary" href="https://www.shopapexel.com/pages/compatibility-guide" target="_blank" rel="noopener noreferrer">APEXEL’s phone compatibility guide ↗</a>. Align the clip with your main rear camera; removing a thick case can help it fit.</>],
  ["Is this a one-time purchase?", "Yes. Each hardware package is a one-time purchase in USD, with shipping and the digital kit included. Whop securely processes your payment through Smart Ag AI and shows the final total before you pay."],
  ["When will my order arrive?", "Lens and soil meter packages have an estimated delivery of 2–4 weeks; the tent is 3–4 weeks, for the United States and Canada. We send tracking after dispatch so you can follow your order."],
  ["How do I access my guide?", "After successful payment, open your Whop purchase using the email you checked out with. Start Here and Quickstart Files contain your guide, worksheets and observation log."],
  ["Can I get help with my order?", "Email support@mastergrowbot.com for setup or order help. Unused, unopened hardware can be returned within 30 days of delivery; contact us first for instructions. You pay return shipping except for damaged or incorrect goods."],
] as const;
export default function GrowTech() {
  useEffect(() => { captureGrowTechAttribution(); trackEvent("growtech_offer_view", {product_id:offer.productId,value:119,currency:"USD",availability:offer.availability}); }, []);
  return <div className="premium-site lens-page">
    <SEOHead title="MasterGrowbot Shop: Digital Guides & GrowTech Equipment" description="Choose the $29 complete digital Playbook kit, $19 Equipment Quickstart, or $119 APEXEL lens with the complete digital kit. Preview before buying." canonicalUrl="https://www.mastergrowbot.com/grow-tech" ogImage="https://www.mastergrowbot.com/images/grow-tech/lens-launch/product.webp" />
    <Helmet><script type="application/ld+json">{JSON.stringify({ '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'GrowTech', url: 'https://www.mastergrowbot.com/grow-tech', hasPart: { '@type': 'WebPage', name: offer.name, url: 'https://www.mastergrowbot.com/grow-tech/apexel-macro-lens-kit' } })}</script></Helmet>
    <LandingNav growTechMode/><main>
      <nav className="lens-wrap shop-jump-links" aria-label="Shop categories"><a href="#digital-guides">Digital guides · from $19</a><a href="#lens-offer">Lens + complete kit · $119</a><a href="#soil-meter">Soil meter · $99</a><a href="#grow-tent">Tent · $289</a></nav>
      <ShopDigitalOffers />
      <section id="lens-offer" className="lens-wrap lens-hero"><div className="lens-intro"><p className="lens-eyebrow">GROWTECH · LENS + LIGHT + OBSERVATION KIT</p><h1>Closer plant photos.<br/><em>A clearer way to keep track.</em></h1><p>Get the APEXEL 10–20X macro lens with LED light and the complete $29 digital Playbook kit. Quickstart, prompts, workbook and observation templates included.</p><div className="lens-price"><strong>$119</strong><span>USD · One-time purchase</span></div><p className="lens-small">{offer.fulfillmentNote}</p><OfferAction location="growtech:hero"/><a className="lens-secondary" href="#compatibility">Check phone compatibility ↓</a><p className="lens-small">Whop payment · Phone not included · No app subscription</p><nav aria-label="More GrowTech products" className="lens-product-links"><Link to="/grow-tech/apexel-macro-lens-kit">Full lens package details →</Link><a href="#soil-meter">Soil meter · $99 ↓</a><a href="#grow-tent">2×2 tent · $289 ↓</a></nav></div><LensGallery/></section>
      <section className="lens-wrap lens-section" id="contents"><p className="lens-eyebrow">ONE PACKAGE. A SIMPLE ROUTINE.</p><h2>Look closer. Save the context.</h2><p className="lens-lede">The lens helps you get closer to small plant details. The guide helps you repeat the setup and keep notes beside each photo.</p><div className="lens-grid"><article><span className="lens-step">01</span><h3>APEXEL lens + LED light</h3><p>Adjustable 10–20X ZoomMacro lens, LED ring light and phone mounting clip. Phone not included. Check your phone and case compatibility before ordering.</p></article><article><span className="lens-step">02</span><h3>MasterGrowbot Quickstart</h3><p>The complete $29 digital kit includes the 32-page Playbook, 8 copy-ready prompts, 8-page workbook and 12-page Equipment Quickstart. Preview real pages before buying.</p></article><article><span className="lens-step">03</span><h3>Worksheets + observation log</h3><p>Two printable/fillable worksheets and a CSV log for dates, equipment settings and observations. Use them without an app subscription.</p></article></div><p className="lens-small">Phones, plants, tents and props in the illustrations are not included.</p></section>
      <LensTestimonials/>
      <section className="lens-wrap lens-section lens-split" id="compatibility"><div><p className="lens-eyebrow">CHECK THE FIT FIRST</p><h2>Your phone. Your setup.</h2><p>Check your exact phone model, whether the clip reaches the main rear camera and whether your case prevents alignment. Macro focus needs a close, steady working position.</p><a className="lens-button lens-outline" href="https://www.shopapexel.com/pages/compatibility-guide" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent("growtech_compatibility_click",{product_id:offer.productId})}>Open APEXEL’s compatibility guide ↗</a></div><aside className="lens-panel"><h3>See actual product evidence</h3><p>Inspect APEXEL’s photos, specifications and demonstrations to judge whether this lens suits the detail you need.</p><a className="lens-secondary" href="https://www.shopapexel.com/products/zoommacro-macro-lens?variant=48462996472116" target="_blank" rel="noopener noreferrer">View the manufacturer’s demonstration ↗</a><p className="lens-small">Our gallery contains illustrations, not customer photos or optical performance demonstrations.</p></aside></section>
      <section className="lens-wrap lens-section lens-split" id="guide-preview"><div><p className="lens-eyebrow">INSPECT THE DIGITAL KIT</p><h2>More than another loose photo.</h2><p>Keep the date, the plant and the setup with your observations. The guide and templates give you a repeatable place to start.</p><a className="lens-button lens-outline" href="/downloads/grow-tech/quickstart-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent("growtech_guide_preview",{product_id:offer.productId})}><Download size={18}/> Preview the guide sample</a></div><div className="lens-panel"><img src="/images/playbook/quickstart-cover-v4.webp" alt="MasterGrowbot Equipment Quickstart guide cover illustration" width={480} height={480} loading="lazy" className="lens-guide-cover"/><p className="lens-small">4 PDFs · 8 copy-ready prompts · CSV log<br/>Files through Whop after confirmed payment.</p></div></section>
      <section className="lens-wrap lens-section lens-split" id="soil-meter"><div><p className="lens-eyebrow">SOIL OBSERVATIONS</p><h2>A reading, with room for your notes.</h2><p>A standalone six-function meter, plus the MasterGrowbot Quickstart and templates. Check soil moisture, pH, temperature, fertility, light and ambient humidity. Treat readings as observations; accuracy depends on conditions and handling.</p><div className="lens-price"><strong>$99</strong><span>USD · One-time purchase</span></div><p className="lens-small">{soilGuideOffer.fulfillmentNote}</p><OfferAction product={soilGuideOffer} location="growtech:soil"/><p className="lens-small">White-cased meter with two probes. No automatic app syncing. Plants and other props are not included.</p></div><LensGallery kind="soil"/></section>
      <section className="lens-wrap lens-section lens-split" id="grow-tent"><div><p className="lens-eyebrow">A SPACE FOR YOUR SMALL GROW</p><h2>Start compact. Keep it organized.</h2><p>An unbranded 2×2 tent with reflective lining, a zip doorway and floor tray. A dedicated space for seedlings and compact plants, plus the same MasterGrowbot Quickstart and observation templates.</p><div className="lens-price"><strong>{growTentOffer.price}</strong><span>USD · One-time purchase</span></div><p className="lens-small">{growTentOffer.fulfillmentNote}</p><OfferAction product={growTentOffer} location="growtech:tent"/><p className="lens-small">60 × 60 × 140 cm (approximately 24 × 24 × 55 in). Tent only: lights, fans, ducting, pots and plants are not included.</p></div><LensGallery kind="tent"/></section>
      <section className="lens-wrap lens-section" id="delivery"><p className="lens-eyebrow">BEFORE YOU ORDER</p><h2>Clear delivery. Real support.</h2><div className="lens-grid"><article><h3>Delivery at a glance</h3><p>US & Canada: lens and meter, estimated 2–4 weeks from payment. Tent, estimated 3–4 weeks from payment. For remote addresses or a particular deadline, contact us before ordering.</p><p>Shipping included. Prices in USD; sales tax shown at checkout. Canadian import charges, if assessed, are extra.</p></article><article><h3>Guide now. Tracking to follow.</h3><p>Get the guide and templates through Whop after confirmed payment. Hardware is sourced to order; tracking is provided after dispatch.</p></article><article><h3>Help and returns</h3><p>Email <a href="mailto:support@mastergrowbot.com">support@mastergrowbot.com</a> for fit, delivery or access help. Contact us before returning unused, unopened hardware within 30 days of delivery. You pay return shipping, except for damaged or incorrect goods.</p></article></div></section>
      <section className="lens-wrap lens-section" id="faq"><p className="lens-eyebrow">CHOOSE WITH CONFIDENCE</p><h2>Find the right tool for your next observation.</h2>{questions.map(([question,answer])=><details key={question} className="lens-faq"><summary>{question}</summary><p>{answer}</p></details>)}</section>
      <section className="lens-wrap lens-section lens-final"><p className="lens-eyebrow">THE GROWTECH LENS PACKAGE</p><h2>A closer look, with a clearer record.</h2><p>APEXEL lens + LED light. Complete MasterGrowbot digital Playbook kit included.</p><p className="lens-price"><strong>$119</strong><span>USD · One time</span></p><OfferAction location="growtech:final"/></section>
    </main><LandingFooter/><div className="lens-sticky"><span><strong>$119</strong> · Lens + guide</span><OfferAction location="growtech:sticky"/></div>
  </div>;
}
