import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowRight, Check, Download, Camera, ClipboardList, ScanSearch, FileCheck2 } from 'lucide-react';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import SEOHead from '@/components/SEOHead';
import { usePlaybookOffer } from '@/hooks/usePlaybookOffer';
import { PLAYBOOK_LAUNCH_END } from '@/data/playbook';
import { trackEvent } from '@/lib/analytics';
import '@/components/landing/premium.css';

const contents = [
  ['24-page illustrated Playbook', 'A photo-to-record workflow, evidence quality checks, worked examples and a complete first-session checklist.'],
  ['8 copy-ready AI prompts', 'Describe photographs, organize readings, compare records, audit uncertainty and create a concise handoff. Included in the book and as a separate text file.'],
  ['6-page field workbook', 'An example packet plus printable and fillable session, comparison, review and journal sheets.'],
  ['9-page Equipment Quickstart', 'The refreshed $19 guide is included. Learn equipment handling, photo consistency, manual readings and troubleshooting.'],
  ['2 quickstart worksheets + CSV log', 'Keep records in a PDF reader, on paper or in a spreadsheet. Your original files and reviewed notes stay in your control.'],
];
const faq = [
  ['Who is this for?', 'Careful plant observers, home growers and small craft cultivators who want useful photographs and organized records. Beginners get a clear first session; equipment enthusiasts get comparison checks; experienced users get a review and handoff workflow.'],
  ['Does this teach cultivation or guarantee results?', 'No. This product covers observation, equipment records and critical use of AI. It does not include cultivation instructions, treatment recipes, diagnosis or promises of higher yield or quality.'],
  ['What do I need?', 'A phone or camera and somewhere to save records are enough to begin. An image-capable AI tool is optional; any AI account fees, hardware and app subscriptions are separate.'],
  ['Do I need the $19 Quickstart too?', 'No. Its refreshed nine-page edition, two worksheets and CSV log are included with this Playbook purchase. The $19 guide remains a smaller option for equipment handling alone.'],
  ['When does the launch price end?', 'The $42 launch price ends October 16, 2026 at 11:59 p.m. Mexico City time. The regular one-time price is $89 after that fixed deadline. The countdown does not restart when you return.'],
  ['How will I receive it?', 'Use the Whop account from checkout to open Start Here and download the files. This is a digital purchase with no physical shipment or recurring guide subscription. Purchase terms are available at checkout.'],
];
export default function Playbook() {
  const offer = usePlaybookOffer();
  useEffect(() => { trackEvent('playbook_view', { page: '/playbooks' }); }, []);
  const days = Math.floor(offer.remaining / 86400000);
  const hours = Math.floor(offer.remaining / 3600000) % 24;
  const minutes = Math.floor(offer.remaining / 60000) % 60;
  const seconds = Math.floor(offer.remaining / 1000) % 60;
  function cta(location: string) { trackEvent('playbook_checkout_open', { cta_location: location, value: offer.price, currency: 'USD', product: 'ai-plant-observation-playbook' }); }
  return <div className="premium-site min-h-screen bg-[#030906] text-white">
    <SEOHead title="AI Plant Observation Playbook | MasterGrowbot" description="Clearer photos. Better records. AI answers you can check. Get a 24-page Playbook, 8 prompts, fillable workbook and the GrowTech Equipment Quickstart." canonicalUrl="https://www.mastergrowbot.com/playbooks" />
    <Helmet><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'Product',name:'AI Plant Observation Playbook',description:'Digital observation workflow with 24-page PDF, 8 prompts, 6-page workbook and Equipment Quickstart.',image:'https://www.mastergrowbot.com/images/playbook/observation-cover.webp',brand:{'@type':'Brand',name:'MasterGrowbot'},offers:{'@type':'Offer',price:offer.price,priceCurrency:'USD',url:'https://www.mastergrowbot.com/playbooks',availability:'https://schema.org/InStock',...(offer.isLaunch ? {priceValidUntil:PLAYBOOK_LAUNCH_END}: {})}})}</script></Helmet>
    <LandingNav />
    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1.1fr_.9fr]">
        <div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">MasterGrowbot field guides · Digital edition</p><h1 className="mt-5 text-5xl font-bold leading-[1.08] tracking-tight sm:text-6xl">Clearer photos.<br />Better records.<br /><span className="text-emerald-300">AI you can check.</span></h1><p className="mt-6 text-xl leading-8 text-white/75">The AI Plant Observation Playbook turns scattered photos and readings into a repeatable record. Know what you saw, what is missing and what an AI answer actually supports.</p><p className="mt-5 leading-7 text-white/60">For home growers, equipment enthusiasts and small craft cultivators who value visual proof over another confident guess.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link onClick={()=>cta('hero')} to="/playbooks/checkout" className="inline-flex min-h-14 items-center gap-3 rounded-full bg-emerald-300 px-7 py-4 font-bold text-black">Get the complete kit · ${offer.price} <ArrowRight size={18}/></Link><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent('playbook_sample_open',{cta_location:'hero'})} className="inline-flex min-h-12 items-center gap-2 text-sm font-semibold text-emerald-300 underline underline-offset-4"><Download size={16}/>Read the free 4-page sample</a></div><p className="mt-4 text-sm text-white/55">One-time payment · PDF + worksheets + prompts · No app subscription included</p>{offer.isLaunch ? <div className="mt-6 rounded-xl border border-emerald-300/20 bg-emerald-950/35 p-4"><p className="text-sm font-semibold">Launch price $42. Regular price $89 after October 16.</p><p className="mt-2 font-mono text-lg tabular-nums" aria-label="Time remaining in launch offer">{days}d {hours}h {minutes}m {seconds}s remaining</p><p className="mt-1 text-xs leading-5 text-white/60">Ends October 16, 2026 at 11:59 p.m. Mexico City time. One fixed deadline.</p></div>:null}</div>
        <figure className="mx-auto w-full max-w-sm rotate-1 overflow-hidden rounded-2xl border border-white/15 shadow-[0_24px_90px_rgba(0,0,0,.5)]"><div className="relative"><img src="/images/playbook/observation-cover.webp" alt="Editorial photograph of plant leaves, an observation notebook, magnifying lens and reference photographs" width={1024} height={1536} className="w-full" loading="eager"/><div className="absolute inset-x-0 top-0 bg-[#10271f] px-7 py-9"><p className="text-xs font-bold tracking-widest text-emerald-200">MASTERGROWBOT</p><p className="mt-5 text-4xl font-bold leading-tight">AI Plant<br/>Observation<br/>Playbook</p><p className="mt-5 text-sm leading-6 text-white/70">Photographs. Records.<br/>Prompts. Human judgment.</p></div></div><figcaption className="bg-[#10271f] px-7 py-4 text-xs font-semibold tracking-wider text-white/70">24-PAGE GUIDE + COMPLETE REFERENCE KIT</figcaption></figure>
      </section>
      <section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-9 sm:px-8 md:grid-cols-3">{[['Start without overwhelm','One subject. One question. One completed session.'],['Get more from your gear','Record the value, unit and context before comparing.'],['Share a clearer history','Keep evidence, interpretations and unknowns separate.']].map(([title,text])=><div key={title}><h2 className="font-semibold text-emerald-200">{title}</h2><p className="mt-2 text-sm leading-6 text-white/65">{text}</p></div>)}</div></section>
      <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">A practical system, not another pile of tips</p><h2 className="mt-4 text-4xl font-bold tracking-tight">A record you can trust starts here.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[Camera,'Capture','An overview, a detail and a clear focus point.'],[ClipboardList,'Record','Dates, filenames, exact readings and missing context.'],[ScanSearch,'Organize','Eight bounded prompts with review instructions.'],[FileCheck2,'Review','Check the answer against your originals. Save the limits.']].map(([Icon,title,text],i)=>{ const StepIcon=Icon as typeof Camera; return <article key={String(title)} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><StepIcon className="text-emerald-300" size={24}/><p className="mt-7 text-xs text-white/45">0{i+1}</p><h3 className="mt-2 text-xl font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-white/65">{String(text)}</p></article>;})}</div></section>
      <section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8"><div className="grid gap-12 lg:grid-cols-[1fr_1.2fr]"><div><h2 className="text-4xl font-bold tracking-tight">Everything in<br/>your download.</h2><p className="mt-5 leading-7 text-white/65">Designed for people who like precise tools and visible evidence. Read, fill in the workbook and use the same workflow for your next session.</p><p className="mt-5 text-sm leading-6 text-white/55">The Equipment Quickstart is included. You do not need to buy the $19 guide separately.</p><Link to="/about" className="mt-6 inline-block text-sm font-semibold text-emerald-300 underline underline-offset-4">Meet Eli Duffy and the mission behind MasterGrowbot</Link></div><div className="space-y-6">{contents.map(([title,text])=><article key={title} className="flex gap-4 border-b border-white/10 pb-6"><Check className="mt-1 shrink-0 text-emerald-300" size={20}/><div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-7 text-white/65">{text}</p></div></article>)}</div></div></section>
      <section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8"><div className="rounded-3xl border border-emerald-300/20 bg-emerald-950/35 p-7 sm:p-12"><h2 className="text-3xl font-bold">Try the format before you buy.</h2><p className="mt-4 max-w-2xl leading-7 text-white/70">The sample includes the cover, observation loop, a copy-ready image prompt and the first-session checklist. These are actual pages from the Playbook.</p><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent('playbook_sample_open',{cta_location:'preview'})} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-full border border-emerald-300/40 px-6 py-3 font-semibold text-emerald-200"><Download size={18}/>Open the free sample</a></div></section>
      <section className="mx-auto max-w-3xl px-5 pb-20 sm:px-8"><h2 className="text-3xl font-bold">Frequently asked questions</h2>{faq.map(([question,answer])=><article key={question} className="mt-8"><h3 className="text-xl font-semibold">{question}</h3><p className="mt-3 leading-7 text-white/65">{answer}</p></article>)}</section>
      <section id="quickstart-guides" className="mx-auto max-w-6xl scroll-mt-24 px-5 pb-20 sm:px-8"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">The Quickstart library</p><h2 className="mt-4 text-4xl font-bold">Choose the guide you need.</h2><p className="mt-5 max-w-2xl leading-7 text-white/65">Start with a free setup sheet, choose the smaller equipment guide, or get the full AI observation workflow above. Basic equipment setup stays free.</p><div className="mt-8 grid gap-6 md:grid-cols-2"><article className="rounded-2xl border border-white/15 bg-white/[.03] p-7"><p className="text-sm font-semibold text-emerald-300">$19 once · Digital download</p><h3 className="mt-3 text-2xl font-bold">GrowTech Equipment Quickstart</h3><p className="mt-4 leading-7 text-white/65">Nine-page guide to phone-lens handling, manual readings, observation records and troubleshooting. Includes two printable and fillable worksheets and a CSV log.</p><p className="mt-4 text-sm text-white/55">Already buying the premium Playbook? This guide is included.</p><Link to="/grow-tech/checkout/quickstart-guide" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-emerald-300 px-6 py-3 font-bold text-black">Get the Quickstart · $19 →</Link><a href="/downloads/grow-tech/quickstart-sample.pdf" target="_blank" rel="noopener noreferrer" className="mt-5 block text-sm font-semibold text-emerald-300 underline underline-offset-4">Read its free two-page sample</a></article><article className="rounded-2xl border border-white/15 bg-white/[.03] p-7"><p className="text-sm font-semibold text-emerald-300">Free · No purchase required</p><h3 className="mt-3 text-2xl font-bold">Equipment setup sheets</h3><p className="mt-4 leading-7 text-white/65">A short reference for each tool. Follow the manufacturer manual for model-specific operation and calibration.</p><ul className="mt-5 space-y-4">{[['Scout Camera phone-lens setup','scout-camera-setup.pdf'],['Environment Monitor setup','environment-monitor-setup.pdf'],['Soil Health Meter setup','soil-health-meter-setup.pdf']].map(([label,file])=><li key={file}><a href={`/downloads/grow-tech/${file}`} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-emerald-300 underline underline-offset-4"><Download size={16}/>{label}</a></li>)}</ul><Link to="/grow-tech" className="mt-6 inline-block text-sm text-white/65 underline underline-offset-4">Browse compatible GrowTech equipment →</Link></article></div></section>
      <section className="border-t border-white/10 bg-white/[.025] px-5 py-16 text-center"><h2 className="text-3xl font-bold">Make your next observation count.</h2><p className="mt-4 text-white/65">The complete digital kit. One payment. Your records to keep.</p><Link to="/playbooks/checkout" onClick={()=>cta('final')} className="mt-7 inline-flex min-h-14 items-center gap-3 rounded-full bg-emerald-300 px-8 py-4 font-bold text-black">Get the Playbook · ${offer.price}<ArrowRight size={18}/></Link><p className="mt-4 text-xs text-white/55">General plant observation. No cultivation instructions or guaranteed outcomes.</p></section>
    </main><LandingFooter />
  </div>;
}
