import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import { PLAYBOOK_CONTENT_URL, PLAYBOOK_FILES_URL } from '@/data/playbook';
import '@/components/landing/premium.css';
export default function PlaybookThankYou(){
  return <div className="premium-site min-h-screen bg-[#030906] text-white"><Helmet><title>Your Playbook access | MasterGrowbot</title><meta name="robots" content="noindex,follow"/></Helmet><LandingNav/><main className="mx-auto max-w-3xl px-5 py-20"><p className="text-sm font-semibold text-emerald-300">Digital purchase access</p><h1 className="mt-4 text-4xl font-bold">Find your Playbook files.</h1><p className="mt-6 text-lg leading-8 text-white/70">Check your Whop receipt to confirm payment. Sign in with the same account used at checkout, then open Start Here for the reading order and Files to save your PDFs, prompts and log.</p><div className="mt-9 flex flex-wrap gap-4"><a href={PLAYBOOK_CONTENT_URL} className="rounded-full bg-emerald-300 px-7 py-4 font-bold text-black">Open Start Here →</a><a href={PLAYBOOK_FILES_URL} className="rounded-full border border-white/20 px-7 py-4 font-semibold">Open Files →</a></div><ol className="mt-10 list-inside list-decimal space-y-4 leading-7 text-white/70"><li>Open Edition 3 and complete the first-session checklist on page 3.</li><li>Use the completed record on page 4, then fill in your own workbook session sheet.</li><li>Pick a prompt, check the answer and save your reviewed record.</li></ol><p className="mt-8 text-sm leading-7 text-white/55">These links require purchase access. This page itself does not confirm a payment or unlock files. If access is missing after a successful receipt, contact <a className="text-emerald-300 underline" href="mailto:support@mastergrowbot.com">support@mastergrowbot.com</a>.</p><Link to="/playbooks" className="mt-8 inline-block text-emerald-300 underline">Return to the Playbook</Link></main><LandingFooter/></div>;
}
