import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowRight, Check, Download, Camera, ClipboardList, ScanSearch, FileCheck2, ChevronDown, LockKeyhole } from 'lucide-react';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import SEOHead from '@/components/SEOHead';
import { usePlaybookOffer } from '@/hooks/usePlaybookOffer';
import { PLAYBOOK_LAUNCH_END } from '@/data/playbook';
import { trackEvent } from '@/lib/analytics';
import '@/components/landing/premium.css';

const contents = [
  ['24-page illustrated Playbook', 'Follow the photo-to-record workflow with visual reference cards, worked examples and a first-session checklist.'],
  ['8 copy-ready AI prompts', 'Describe photos, organize readings, compare records and check uncertainty. Copy them from the separate text file when you need them.'],
  ['6-page fillable field workbook', 'Use the completed example as a reference, then fill in your own session, comparison, review and journal sheets. Print them if you prefer paper.'],
  ['9-page Equipment Quickstart', 'Get the complete $19 guide to phone-lens handling, manual readings, photo consistency and troubleshooting. Included in your kit.'],
  ['2 Quickstart worksheets + CSV log', 'Save exact readings and their context in a PDF reader or spreadsheet. Keep the original photos alongside the notes you have checked.'],
];
const setupSheets = [
  ['Scout Camera phone-lens setup', 'scout-camera-setup.pdf'],
  ['Environment Monitor setup', 'environment-monitor-setup.pdf'],
  ['Soil Health Meter setup', 'soil-health-meter-setup.pdf'],
];
const workflow = [
  { icon: Camera, title: 'Capture', text: 'Take an overview and a detail photo you can identify later.' },
  { icon: ClipboardList, title: 'Record', text: 'Save the date, filenames, readings, units and missing context.' },
  { icon: ScanSearch, title: 'Organize', text: 'Use a copy-ready prompt to structure your notes or compare records.' },
  { icon: FileCheck2, title: 'Review', text: 'Check the answer against your originals before saving it.' },
];
const faq = [
  ['Which guide should I choose?', 'Choose the $19 Equipment Quickstart for equipment handling, manual readings and basic recordkeeping. Choose the complete Playbook kit if you also want the AI prompts, illustrated observation workflow and field workbook. The kit already includes the Quickstart.'],
  ['What do I need to get started?', 'A phone or camera and somewhere to save records are enough to begin. To use the photo prompts, choose an AI tool that accepts images. Hardware, AI account fees and app subscriptions are separate.'],
  ['Can I use this without GrowTech equipment?', 'Yes. The observation workflow and workbook work with photos and manually entered readings. The Quickstart includes general handling guidance for the GrowTech tools; use the manual in your box for model-specific operation and calibration.'],
  ['What does the Playbook cover?', 'It covers plant observation, equipment records and careful use of AI to organize evidence. It does not provide cultivation instructions, treatment recipes or diagnosis, and it does not promise higher yield or quality.'],
  ['How do I receive my files?', 'After a successful payment, use the Whop account from checkout to open Start Here and download your files. The kit includes four PDFs, a CSV log and a prompt text file. There is no physical shipment or recurring guide subscription.'],
  ['Can I print the worksheets or fill them in on screen?', 'Yes. The workbook and worksheets are printable and include fillable fields for a compatible PDF reader. Save a copy and reopen it to check that your entries were retained.'],
  ['When does the launch price end?', 'The $42 launch price ends October 16, 2026 at 11:59 p.m. Mexico City time. The regular one-time price is $89 after that fixed deadline. The countdown does not restart when you return.'],
  ['What if I need help with access?', 'Check that you are signed into the Whop account used for payment, then open Start Here from your purchase. For help, use the MasterGrowbot contact page. Purchase and refund terms are available at checkout.'],
];
const primaryButton = 'inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-emerald-300 px-6 py-3 font-bold text-[#062014] transition hover:bg-emerald-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-200';
const sampleLink = 'inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-emerald-200 underline underline-offset-4 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-200';

export default function Playbook() {
  const offer = usePlaybookOffer();
  const heroAction = useRef<HTMLDivElement>(null);
  const finalAction = useRef<HTMLElement>(null);
  const [pastHero, setPastHero] = useState(false);
  const [finalVisible, setFinalVisible] = useState(false);
  useEffect(() => {
    trackEvent('playbook_view', { page: '/playbooks' });
    if (!('IntersectionObserver' in window)) return;
    const heroObserver = new IntersectionObserver(([entry]) => setPastHero(!entry.isIntersecting && entry.boundingClientRect.bottom < 0));
    const finalObserver = new IntersectionObserver(([entry]) => setFinalVisible(entry.isIntersecting));
    if (heroAction.current) heroObserver.observe(heroAction.current);
    if (finalAction.current) finalObserver.observe(finalAction.current);
    return () => { heroObserver.disconnect(); finalObserver.disconnect(); };
  }, []);
  const days = Math.floor(offer.remaining / 86400000);
  const hours = Math.floor(offer.remaining / 3600000) % 24;
  const minutes = Math.floor(offer.remaining / 60000) % 60;
  function chooseGuide(product: 'premium' | 'quickstart', location: string) {
    const premium = product === 'premium';
    const price = premium ? offer.price : 19;
    const itemId = premium ? 'ai-plant-observation-playbook' : 'growtech_equipment_quickstart';
    trackEvent('select_item', {
      item_list_id: 'playbooks-library', item_list_name: 'Playbooks library', checkout_source_page: '/playbooks',
      cta_location: location, value: price, currency: 'USD',
      items: [{ item_id: itemId, item_name: premium ? 'AI Plant Observation Playbook' : 'GrowTech Equipment Quickstart', item_category: 'Digital guides', price, quantity: 1 }],
    });
    trackEvent(premium ? 'playbook_checkout_open' : 'quickstart_checkout_open', { cta_location: location, value: price, currency: 'USD', product: itemId, page: '/playbooks' });
  }
  function openSample(product: 'premium' | 'quickstart', location: string) {
    trackEvent(product === 'premium' ? 'playbook_sample_open' : 'quickstart_sample_open', { cta_location: location, page: '/playbooks', product });
  }
  return <div className="premium-site min-h-screen bg-[#030906] pb-24 text-white lg:pb-0">
    <SEOHead title="Playbooks & Quickstart Guides | MasterGrowbot" description="Choose the $19 Equipment Quickstart or the complete AI Plant Observation Playbook kit. Preview real pages, compare what's included and download free setup sheets." canonicalUrl="https://www.mastergrowbot.com/playbooks" />
    <Helmet><script type="application/ld+json">{JSON.stringify({ '@context': 'https://schema.org', '@type': 'Product', name: 'AI Plant Observation Playbook', description: 'Digital observation workflow with 24-page PDF, 8 prompts, 6-page workbook and Equipment Quickstart.', image: 'https://www.mastergrowbot.com/images/playbook/observation-cover.webp', brand: { '@type': 'Brand', name: 'MasterGrowbot' }, offers: { '@type': 'Offer', price: offer.price, priceCurrency: 'USD', url: 'https://www.mastergrowbot.com/playbooks', availability: 'https://schema.org/InStock', ...(offer.isLaunch ? { priceValidUntil: PLAYBOOK_LAUNCH_END } : {}) } })}</script></Helmet>
    <LandingNav />
    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[1.15fr_.85fr]">
        <div>
          <p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">MasterGrowbot Playbooks & Quickstart guides</p>
          <h1 className="mt-5 max-w-2xl text-4xl font-bold leading-[1.1] tracking-tight sm:text-6xl">Turn plant photos into <span className="text-emerald-300">a record you can use.</span></h1>
          <p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Know what changed, find the readings behind your notes, and check what an AI answer supports. The AI Plant Observation Playbook gives you the workflow, prompts and worksheets to keep it all together.</p>
          <ul className="mt-6 space-y-3 text-sm leading-6 text-white/80">{['Follow a clear first session, even if you are new to recordkeeping.', 'Copy eight AI prompts instead of starting from a blank chat.', 'Keep photos, readings and checked notes ready for your next review.'].map(text => <li key={text} className="flex gap-3"><Check size={18} className="mt-1 shrink-0 text-emerald-300" aria-hidden="true" />{text}</li>)}</ul>
          <div ref={heroAction} className="mt-7"><div className="flex flex-wrap items-center gap-x-4 gap-y-2"><p className="text-4xl font-bold">${offer.price}<span className="ml-2 text-sm font-normal text-white/60">USD, one-time</span></p>{offer.isLaunch ? <span className="rounded-full border border-emerald-300/25 px-3 py-1 text-xs font-semibold text-emerald-200">Launch price · $47 less than the post-launch price</span> : null}</div><Link onClick={() => chooseGuide('premium', 'hero')} to="/playbooks/checkout" className={`${primaryButton} mt-5 w-full sm:w-auto`}>Get the complete Playbook kit <ArrowRight size={18} aria-hidden="true" /></Link><p className="mt-3 text-xs leading-5 text-white/60">Digital files through Whop after payment. The $19 Quickstart is included.</p></div>
          <div className="mt-4 flex flex-wrap gap-x-6 gap-y-1"><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={() => openSample('premium', 'hero')} className={sampleLink}><Download size={16} aria-hidden="true" />Read the free sample</a><a href="#quickstart-guides" onClick={() => trackEvent('playbook_compare_open', { cta_location: 'hero' })} className={sampleLink}>Compare all guides <ChevronDown size={16} aria-hidden="true" /></a></div>
          {offer.isLaunch ? <div className="mt-5 border-l-2 border-emerald-300/50 pl-4"><p className="text-sm text-white/75">Launch ends in <span className="font-mono font-semibold tabular-nums text-emerald-200">{days}d {hours}h {minutes}m</span></p><p className="mt-1 text-xs leading-5 text-white/55">$89 after October 16, 2026, 11:59 p.m. Mexico City time.</p></div> : null}
        </div>
        <figure className="mx-auto w-full max-w-xs overflow-hidden rounded-2xl border border-white/15 shadow-[0_24px_90px_rgba(0,0,0,.5)] sm:max-w-sm"><div className="relative"><img src="/images/playbook/observation-cover.webp" alt="Plant leaves, an observation notebook, magnifying lens and reference photographs on the Playbook cover" width={1024} height={1536} className="w-full" loading="eager" /><div className="absolute inset-x-0 top-0 bg-[#10271f] px-7 py-8"><p className="text-xs font-bold tracking-widest text-emerald-200">MASTERGROWBOT</p><p className="mt-4 text-4xl font-bold leading-tight">AI Plant<br />Observation<br />Playbook</p><p className="mt-4 text-sm leading-6 text-white/70">Photographs. Records.<br />Prompts. Human judgment.</p></div></div><figcaption className="bg-[#10271f] px-7 py-4 text-xs font-semibold tracking-wider text-white/70">24-PAGE PLAYBOOK + COMPLETE DIGITAL KIT</figcaption></figure>
      </section>
      <div className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto flex max-w-6xl flex-wrap justify-center gap-x-8 gap-y-3 px-5 py-5 text-sm text-white/75">{['One-time purchase', 'Printable + fillable PDFs', 'No guide subscription', 'Preview before you buy'].map(text => <span key={text} className="inline-flex items-center gap-2"><Check size={16} className="text-emerald-300" aria-hidden="true" />{text}</span>)}</div></div>
      <section id="quickstart-guides" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-16 sm:px-8 sm:py-20">
        <p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Choose your starting point</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">The right guide for what you need next.</h2><p className="mt-4 max-w-2xl leading-7 text-white/65">Equipment basics, the complete AI observation workflow, or a free setup reference. Compare them here so you only buy what you need.</p>
        <div className="mt-9 grid items-stretch gap-5 lg:grid-cols-3">
          <article className="order-2 flex flex-col rounded-2xl border border-white/15 bg-white/[.03] p-6 lg:order-1"><p className="text-xs font-bold uppercase tracking-widest text-white/55">Equipment essentials</p><h3 className="mt-4 text-2xl font-bold">GrowTech Equipment Quickstart</h3><p className="mt-4 text-sm leading-6 text-white/70">For getting comfortable with your tools and keeping useful readings and photos.</p><p className="mt-5 text-3xl font-bold">$19 <span className="text-sm font-normal text-white/55">USD, once</span></p><ul className="my-6 space-y-3 text-sm leading-6 text-white/75">{['9-page equipment handling and troubleshooting guide', '2 printable and fillable worksheets', 'CSV observation log'].map(text => <li key={text} className="flex gap-2"><Check size={17} className="mt-1 shrink-0 text-emerald-300" aria-hidden="true" />{text}</li>)}</ul><p className="mb-5 text-xs leading-5 text-white/55">Choose the complete kit if you also want the AI prompts and field workbook.</p><Link to="/grow-tech/checkout/quickstart-guide" onClick={() => chooseGuide('quickstart', 'comparison')} className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-emerald-300/40 px-5 py-3 font-bold text-emerald-200 transition hover:bg-emerald-300/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-200">Get the Quickstart · $19 <ArrowRight size={16} aria-hidden="true" /></Link><a href="/downloads/grow-tech/quickstart-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={() => openSample('quickstart', 'comparison')} className={`${sampleLink} mt-3 justify-center`}>Preview 2 real pages</a></article>
          <article className="order-1 flex flex-col rounded-2xl border-2 border-emerald-300/60 bg-[#10271f] p-6 shadow-[0_12px_50px_rgba(16,185,129,.08)] lg:order-2"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Complete workflow + Quickstart included</p><h3 className="mt-4 text-2xl font-bold">AI Plant Observation Playbook kit</h3><p className="mt-4 text-sm leading-6 text-white/75">For organizing your observations and using AI with evidence you can check.</p><p className="mt-5 text-3xl font-bold">${offer.price} <span className="text-sm font-normal text-white/60">USD, once</span></p><ul className="my-6 space-y-3 text-sm leading-6 text-white/85">{['Everything in the $19 Quickstart', '24-page illustrated observation Playbook', '8 copy-ready AI prompts + text file', '6-page printable and fillable field workbook'].map(text => <li key={text} className="flex gap-2"><Check size={17} className="mt-1 shrink-0 text-emerald-300" aria-hidden="true" />{text}</li>)}</ul><p className="mb-5 text-xs leading-5 text-emerald-200">{offer.isLaunch ? 'For $23 more than the Quickstart, get the full kit during launch.' : 'The Equipment Quickstart is included. Buy the kit once.'}</p><Link to="/playbooks/checkout" onClick={() => chooseGuide('premium', 'comparison')} className={`${primaryButton} mt-auto`}>Get the complete kit · ${offer.price} <ArrowRight size={16} aria-hidden="true" /></Link><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={() => openSample('premium', 'comparison')} className={`${sampleLink} mt-3 justify-center`}>Preview 4 real pages</a></article>
          <article className="order-3 flex flex-col rounded-2xl border border-white/15 bg-white/[.03] p-6"><p className="text-xs font-bold uppercase tracking-widest text-white/55">Basic setup references</p><h3 className="mt-4 text-2xl font-bold">Free equipment setup sheets</h3><p className="mt-4 text-sm leading-6 text-white/70">For a short reference when setting up a camera lens, monitor or meter.</p><p className="mt-5 text-3xl font-bold">Free <span className="text-sm font-normal text-white/55">No purchase required</span></p><ul className="my-6 space-y-3">{setupSheets.map(([label, file]) => <li key={file}><a href={`/downloads/grow-tech/${file}`} target="_blank" rel="noopener noreferrer" onClick={() => trackEvent('guide_download', { page: '/playbooks', guide: file, cta_location: 'comparison' })} className={sampleLink}><Download size={16} className="shrink-0" aria-hidden="true" />{label}</a></li>)}</ul><p className="mb-5 text-xs leading-5 text-white/55">Follow the manual in your box for model-specific operation and calibration.</p><Link to="/grow-tech" className="mt-auto inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 px-5 py-3 text-sm font-semibold text-white/75 hover:border-emerald-300/40">Browse GrowTech equipment</Link></article>
        </div><p className="mt-5 text-center text-sm text-white/60">Already choosing the complete kit? You do not need to buy the Quickstart separately.</p>
      </section>
      <section id="inside-the-playbook" className="border-y border-white/10 bg-[#09150f] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">See the pages before you pay</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">A workflow to follow.<br />A prompt to copy.</h2><p className="mt-5 leading-7 text-white/70">These are actual pages from the Playbook. The free sample includes the cover, observation loop, an image prompt and the first-session checklist.</p><p className="mt-4 leading-7 text-white/65">Use the loop to organize a session. Use the prompt to ask for a structured description, then check that answer against the photo you supplied.</p><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={() => openSample('premium', 'preview')} className={`${sampleLink} mt-6`}><Download size={18} aria-hidden="true" />Read the 4-page sample PDF</a></div><div className="grid grid-cols-2 items-start gap-3 sm:gap-5">{[['observation-loop-preview.webp', 'The four-step observation loop, as printed in the Playbook', 'The observation workflow'], ['ai-prompt-preview.webp', 'Copy-ready photo-description prompt and review instructions from the Playbook', 'A copy-ready AI prompt']].map(([file, alt, caption]) => <figure key={file}><a href="/downloads/playbook/playbook-sample.pdf" target="_blank" rel="noopener noreferrer" onClick={() => openSample('premium', 'page_preview')} className="block overflow-hidden rounded-lg border border-white/20 shadow-xl transition hover:-translate-y-1 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-200"><img src={`/images/playbook/${file}`} alt={alt} width={612} height={792} className="w-full" loading="lazy" /></a><figcaption className="mt-3 text-xs leading-5 text-white/60">{caption}</figcaption></figure>)}</div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-20"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Your complete download</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Open it. Use it.<br />Keep your next session organized.</h2><p className="mt-5 leading-7 text-white/65">Start with the checklist, use the worked example, then complete your own record. The files work together so your photos and notes stay understandable when you return to them.</p><Link to="/playbooks/checkout" onClick={() => chooseGuide('premium', 'contents')} className={`${primaryButton} mt-7`}>Get all six files · ${offer.price} <ArrowRight size={16} aria-hidden="true" /></Link><p className="mt-3 text-xs text-white/55">Four PDFs, one CSV log and one prompt text file.</p></div><div className="space-y-5">{contents.map(([title, text]) => <article key={title} className="flex gap-4 border-b border-white/10 pb-5"><Check className="mt-1 shrink-0 text-emerald-300" size={20} aria-hidden="true" /><div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-7 text-white/65">{text}</p></div></article>)}</div></div></section>
      <section className="mx-auto max-w-6xl px-5 pb-16 sm:px-8 sm:pb-20"><h2 className="text-3xl font-bold tracking-tight">Your first session has four steps.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{workflow.map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-center justify-between"><Icon className="text-emerald-300" size={24} aria-hidden="true" /><span className="text-xs font-semibold text-white/45">0{index + 1}</span></div><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{text}</p></article>)}</div></section>
      <section className="mx-auto grid max-w-6xl gap-5 px-5 pb-16 sm:px-8 sm:pb-20 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">The MasterGrowbot mission</p><h2 className="mt-4 text-2xl font-bold">Practical AI for people who care about their plants.</h2><p className="mt-4 leading-7 text-white/65">MasterGrowbot brings experience with AI in commercial cultivation into practical tools for home growers and small craft cultivators. This kit focuses on observations you can document, organize and review, with your original records and judgment at the center.</p><Link to="/about" className={`${sampleLink} mt-4`}>Read the MasterGrowbot mission <ArrowRight size={16} aria-hidden="true" /></Link></article><article className="rounded-2xl border border-emerald-300/20 bg-emerald-950/25 p-7"><LockKeyhole className="text-emerald-300" size={24} aria-hidden="true" /><h2 className="mt-4 text-2xl font-bold">Pay once. Download through Whop.</h2><ol className="mt-5 space-y-4 text-sm leading-6 text-white/75"><li><span className="font-semibold text-emerald-200">1. Choose your guide.</span> Review the sample and continue to Whop checkout.</li><li><span className="font-semibold text-emerald-200">2. Complete your payment.</span> Use the same Whop account to access your purchase.</li><li><span className="font-semibold text-emerald-200">3. Open Start Here.</span> Follow the reading order and save your files.</li></ol><p className="mt-5 text-xs leading-5 text-white/55">Digital guides only. Hardware and AI/app subscriptions are separate. Final total and purchase terms appear at checkout.</p></article></section>
      <section className="mx-auto max-w-3xl px-5 pb-16 sm:px-8 sm:pb-20"><h2 className="text-3xl font-bold tracking-tight">Questions before you choose?</h2><div className="mt-7 divide-y divide-white/10 border-y border-white/10">{faq.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 rounded-sm text-lg font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-200 [&::-webkit-details-marker]:hidden"><h3>{question}</h3><ChevronDown className="shrink-0 text-emerald-300 transition group-open:rotate-180" size={20} aria-hidden="true" /></summary><p className="mt-4 pr-3 leading-7 text-white/65">{answer}</p></details>)}</div><p className="mt-6 text-sm text-white/60">Need help choosing? <Link to="/contact" className="text-emerald-200 underline underline-offset-4">Contact MasterGrowbot</Link>.</p></section>
      <section ref={finalAction} className="border-t border-white/10 bg-[#10271f] px-5 py-14 text-center"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">The complete AI observation kit</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Give your next observation a clear record.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-white/70">The illustrated Playbook, eight prompts, fillable workbook and Equipment Quickstart. One purchase, all six files.</p><Link to="/playbooks/checkout" onClick={() => chooseGuide('premium', 'final')} className={`${primaryButton} mt-7`}>Get the complete kit · ${offer.price} <ArrowRight size={18} aria-hidden="true" /></Link><p className="mt-4 text-xs leading-5 text-white/60">USD, one-time. {offer.isLaunch ? 'Launch ends October 16. $89 afterward.' : 'No recurring guide payment.'}</p><a href="#quickstart-guides" className={`${sampleLink} mt-3`}>Prefer equipment essentials? Choose the $19 Quickstart</a></section>
    </main><LandingFooter />
    {pastHero && !finalVisible ? <aside aria-label="Playbook purchase shortcut" className="fixed inset-x-0 bottom-0 z-40 border-t border-emerald-300/25 bg-[#06130d]/95 px-4 pt-3 backdrop-blur-xl lg:hidden" style={{ paddingBottom: 'max(12px, env(safe-area-inset-bottom))' }}><div className="mx-auto flex max-w-xl items-center justify-between gap-3"><div><p className="text-sm font-bold">Complete kit · ${offer.price}</p><a href="#quickstart-guides" className="inline-flex min-h-8 items-center text-xs text-emerald-200 underline underline-offset-4">Compare guides</a></div><Link to="/playbooks/checkout" onClick={() => chooseGuide('premium', 'mobile_sticky')} className={`${primaryButton} shrink-0 px-5 text-sm`}>Get the kit <ArrowRight size={16} aria-hidden="true" /></Link></div></aside> : null}
  </div>;
}
